# Generated by Django 5.0.6 on 2024-07-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='messages',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='time',
        ),
    ]
