# Generated by Django 5.0.6 on 2024-07-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hotel', 'HOTEL'), ('user', 'USER'), ('admin', 'ADMIN')], default='USER', max_length=100),
        ),
    ]
